// Generated by CoffeeScript 1.12.4
(function() {
  ({
    'menu': [
      {
        'label': 'Packages',
        'submenu': [
          {
            'label': 'vnc',
            'submenu': [
              {
                'label': 'Toggle',
                'command': 'vnc:open'
              }
            ]
          }
        ]
      }
    ]
  });

}).call(this);
