// Generated by CoffeeScript 1.12.4
(function() {
  var Vnc, WorkspaceView;

  WorkspaceView = require('atom').WorkspaceView;

  Vnc = require('../lib/vnc');

  describe("Vnc", function() {
    var activationPromise;
    activationPromise = null;
    beforeEach(function() {
      atom.workspaceView = new WorkspaceView;
      return activationPromise = atom.packages.activatePackage('vnc');
    });
    return describe("when the vnc:toggle event is triggered", function() {
      return it("attaches and then detaches the view", function() {
        expect(atom.workspaceView.find('.vnc')).not.toExist();
        atom.workspaceView.trigger('vnc:toggle');
        waitsForPromise(function() {
          return activationPromise;
        });
        return runs(function() {
          expect(atom.workspaceView.find('.vnc')).toExist();
          atom.workspaceView.trigger('vnc:toggle');
          return expect(atom.workspaceView.find('.vnc')).not.toExist();
        });
      });
    });
  });

}).call(this);
